### PR TITLE
Update Automatic1111 to 1.5.1 in Dockerfile, install generative-models to add compatibility for SDXL

### PR DESCRIPTION
**Pull request by mashb1t**
uses the latest release of https://github.com/Stability-AI/generative-models 45c443b316737a4ab6e40413d7794a7f5657c19f

Tested with the official SDXL 1.0 model from https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/blob/main/sd_xl_base_1.0.safetensors and official refiner from https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/blob/main/sd_xl_refiner_1.0.safetensors.
VAE: https://huggingface.co/stabilityai/sdxl-vae/blob/main/sdxl_vae.safetensors

Closes issue #
https://github.com/AbdBarho/stable-diffusion-webui-docker/issues/559

Closes discussion #
https://github.com/AbdBarho/stable-diffusion-webui-docker/discussions/558

### Update versions

- auto: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/68f336bd994bed5442ad95bad6b6ad5564a5409a

### CODE REVIEW

**Comment by mashb1t** [comment]
there still seems to be an issue with accelerate, but it seems to run fine after it automatically restarts once after the error.

> 2023-07-27 20:33:05 [notice] To update, run: pip install --upgrade pip
2023-07-27 20:33:06 /stable-diffusion-webui
2023-07-27 20:33:07 Traceback (most recent call last):
2023-07-27 20:33:07   File "/stable-diffusion-webui/webui.py", line 39, in <module>
2023-07-27 20:33:07     import pytorch_lightning   # noqa: F401 # pytorch_lightning should be imported after torch, but it re-enables warnings on import so import once to disable them
2023-07-27 20:33:07   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/__init__.py", line 35, in <module>
2023-07-27 20:33:07     from pytorch_lightning.callbacks import Callback  # noqa: E402
2023-07-27 20:33:07   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
2023-07-27 20:33:07     from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
2023-07-27 20:33:07   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/callbacks/batch_size_finder.py", line 24, in <module>
2023-07-27 20:33:07     from pytorch_lightning.callbacks.callback import Callback
2023-07-27 20:33:07   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/callbacks/callback.py", line 25, in <module>
2023-07-27 20:33:07     from pytorch_lightning.utilities.types import STEP_OUTPUT
2023-07-27 20:33:07   File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/utilities/types.py", line 27, in <module>
2023-07-27 20:33:07     from torchmetrics import Metric
2023-07-27 20:33:07   File "/usr/local/lib/python3.10/site-packages/torchmetrics/__init__.py", line 14, in <module>
2023-07-27 20:33:07     from torchmetrics import functional  # noqa: E402
2023-07-27 20:33:07   File "/usr/local/lib/python3.10/site-packages/torchmetrics/functional/__init__.py", line 82, in <module>
2023-07-27 20:33:07     from torchmetrics.functional.text.bleu import bleu_score
2023-07-27 20:33:07   File "/usr/local/lib/python3.10/site-packages/torchmetrics/functional/text/__init__.py", line 30, in <module>
2023-07-27 20:33:07     from torchmetrics.functional.text.bert import bert_score  # noqa: F401
2023-07-27 20:33:07   File "/usr/local/lib/python3.10/site-packages/torchmetrics/functional/text/bert.py", line 24, in <module>
2023-07-27 20:33:07     from torchmetrics.functional.text.helper_embedding_metric import (
2023-07-27 20:33:07   File "/usr/local/lib/python3.10/site-packages/torchmetrics/functional/text/helper_embedding_metric.py", line 26, in <module>
2023-07-27 20:33:07     from transformers import AutoModelForMaskedLM, AutoTokenizer, PreTrainedModel, PreTrainedTokenizerBase
2023-07-27 20:33:07   File "/usr/local/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
2023-07-27 20:33:07     from . import dependency_versions_check
2023-07-27 20:33:07   File "/usr/local/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 57, in <module>
2023-07-27 20:33:07     require_version_core(deps[pkg])
2023-07-27 20:33:07   File "/usr/local/lib/python3.10/site-packages/transformers/utils/versions.py", line 117, in require_version_core
2023-07-27 20:33:07     return require_version(requirement, hint)
2023-07-27 20:33:07   File "/usr/local/lib/python3.10/site-packages/transformers/utils/versions.py", line 111, in require_version
2023-07-27 20:33:07     _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
2023-07-27 20:33:07   File "/usr/local/lib/python3.10/site-packages/transformers/utils/versions.py", line 44, in _compare_versions
2023-07-27 20:33:07     raise ImportError(
2023-07-27 20:33:07 ImportError: accelerate>=0.20.3 is required for a normal functioning of this module, but found accelerate==0.18.0.
2023-07-27 20:33:07 Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main

**Comment by cloudaxes** [comment]
Looks like stable-diffusion-webui requires accelerate==0.18.0 (https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/68f336bd994bed5442ad95bad6b6ad5564a5409a/requirements_versions.txt#L3C1) and transformers requires accelerate>=0.20.3  (https://github.com/huggingface/transformers/blob/05cda5df3405e6a2ee4ecf8f7e1b2300ebda472e/setup.py#L101).

This issue should probably be kicked upstairs to Automatic1111, so he can update his accelerate version.  I'm surprised no one there has mentioned it.  For what it's worth, I ran your commit, and I did not experience this error.

**Review by ioniks — APPROVED** [review]

**Comment by cloudaxes** [comment]
Oh ... Stable-Diffusion-Webui requires transformers v4.25.1 which in turn only needs accelerate>=0.10.0 (https://github.com/huggingface/transformers/blob/31d452c68b34c2567b62924ee0df40a83cbc52d5/setup.py#L100)  This wouldn't be the source of the conflict.  @mashb1t, is it possible the error you experienced came from one of your extensions requiring the accelerate?

**Comment by AbdBarho** [comment]
thank you, I will download and test these now.

**Comment by mashb1t** [comment]
I already tested it with no extensions enabled and also no extensions in the folder at all due to the error only appearing on first container start and installation, not restarts after it has started once.
Turned out that this was an issue with my docker image, running `docker compose --profile auto build ` again fixed it. 
It's hard to pinpoint where exactly the issue was caused as i didn't change any commit hashes, but maybe. library in the background somehow changed their requirements, can't tell.

@cloudaxes thank you for testing and providing feedback!
@AbdBarho i don't see a need to pin the accelerate version as it most likely was a local issue of mine.

**Comment by mashb1t** [comment]
@AbdBarho SDXL recommended GPU VRAM is 8GB if that's what you asked for.

"SDXL 1.0 should work effectively on consumer GPUs with 8GB VRAM"
source: https://stability.ai/blog/stable-diffusion-sdxl-1-announcement

**Comment by mashb1t** [comment]
> what are the GPU requirements?

@AbdBarho SDXL recommended GPU VRAM is 8GB if that's what you asked for.

"SDXL 1.0 should work effectively on consumer GPUs with 8GB VRAM"
source: https://stability.ai/blog/stable-diffusion-sdxl-1-announcement

**Comment by AbdBarho** [comment]
Tested and it worked locally with the base model on a 6GB 1060.

Gonna merge and create a new release

Thanks @mashb1t!

**Comment by xwings** [comment]
i tried install and add new extension. it seems like we need pip3 install gradio_client==0.2.7

**Comment by AbdBarho** [comment]
@xwings which extension? this is maybe an extension problem?

**Comment by xwings** [comment]
> @xwings which extension? this is maybe an extension problem?

i was referering to, when you click on the extenstion tab. it did not show the installed component and nothing work in the extension tab

after fix the gradio_client version. it work now

**Comment by AbdBarho** [comment]
hmmm, weird, I did not have this problem at all.

**Pull request merged**
