### PR TITLE
Adding embeddings volume for auto textual inversion

### PR DESCRIPTION
**Pull request by rgriffogoes**
Adding embeddings volume mapping for AUTOMATIC1111, enabling textual inversion feature. As discussed in #93

### CODE REVIEW

**Comment by Interpause** [comment]
For consistency with the existing way the `output` and `cache` folder are gitignored, maybe you could pre-create the `embeddings` folder and then put a `.gitignore` inside it.

**Comment by AbdBarho** [comment]
@rgriffogoes ok so you tried creating a folder with a .gitignore and the UI crashed because it tried to load it as an embedding, correct? Maybe I will create an issue in the main repo load `pt` files only.


Can you link some embedding files I can use for testing?

I think hlky's UI also supports embeddings, maybe we can find a solution that we can use across uis, but that's for the future.

**Comment by rgriffogoes** [comment]
The additional .gitignore file would fail to be loaded but auto1111 app would still run, and with the proper emdedding file I have loaded. 

You can download these in https://huggingface.co/sd-concepts-library?sort_models=downloads#models

Probably it is not allowed to have these in the repo though. 

And they can be .bin as well (not only pt)

**Review by AbdBarho — APPROVED** [review]

**Comment by AbdBarho** [comment]
@rgriffogoes Thanks!

**Pull request merged**
