### PR TITLE
Update versions

### PR DESCRIPTION
**Pull request by kerrytazi**
### Update dependencies for auto.

New `torch` version increases speed on my 4090 up to +100%.

Barely tested. New torch v2 may be incompatible with some extensions and/or features. But I didn't found any yet.

### CODE REVIEW

**Comment by AbdBarho** [comment]
We should do this, but as you said, untested.

https://github.com/AbdBarho/stable-diffusion-webui-docker/discussions/368

**Comment by PassiveLemon** [comment]
I'm down to test the newer versions on my Nvidia GPU. Just let me know what you would like tested.

**Comment by AbdBarho** [comment]
I think the problem would not be with the UI itself (although possible), the problem would be that many extensions are built around the assumption that the UI has pytorch 1.13, and they might crash.

**Comment by LEv145** [comment]
I have not found extensions that broke due to pytorch, perhaps these are related to generation
There was one that broke - https://github.com/richrobber2/canvas-zoom, but it broke because of the UI and now it's fixed

**Comment by LEv145** [comment]
I would be glad to torch 2.0, because it's pretty fast even without xformers

**Comment by cedriking** [comment]
I just tested this version on my Nvidia GPU and everything is working without issues from my side. Pretty fast compared to the previous one too!

**Pull request closed without merging**
