### PR TITLE
Upgrade invoke to v3.3.0post3

### LINKED ISSUE #553: Invoke build exits with error code 1 - known torchmetrics version mismatch
**I dont believe this is previously reported here**

- [x ] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

**Which UI**

invoke

**Hardware / Software**

- OS: [Windows 11 Pro]

**Steps to Reproduce**

1. sudo docker compose --profile invoke up --build

**Additional context**

https://github.com/invoke-ai/InvokeAI/issues/3658
https://github.com/invoke-ai/InvokeAI/issues/3700

### LINKED ISSUE #595: ImportError: cannot import name '_compare_version' from 'torchmetrics.utilities.imports'
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

I think this is just me. But running into an issue and hoping someone else knows how to fix it. Can't find the issue online. Anyway. Stable diffusion web-ui has been working perfectly on my machine for ages, but recently tried to start it again and am getting stuck with this error:

```
webui-docker-invoke-1  | Traceback (most recent call last):
webui-docker-invoke-1  |   File "/opt/conda/bin/invokeai-configure", line 5, in <module>
webui-docker-invoke-1  |     from ldm.invoke.config.invokeai_configure import main
webui-docker-invoke-1  |   File "/InvokeAI/ldm/invoke/config/invokeai_configure.py", line 40, in <module>
webui-docker-invoke-1  |     from ..args import PRECISION_CHOICES, Args
webui-docker-invoke-1  |   File "/InvokeAI/ldm/invoke/args.py", line 100, in <module>
webui-docker-invoke-1  |     from ldm.invoke.conditioning import split_weighted_subprompts
webui-docker-invoke-1  |   File "/InvokeAI/ldm/invoke/conditioning.py", line 18, in <module>
webui-docker-invoke-1  |     from .generator.diffusers_pipeline import StableDiffusionGeneratorPipeline
webui-docker-invoke-1  |   File "/InvokeAI/ldm/invoke/generator/__init__.py", line 4, in <module>
webui-docker-invoke-1  |     from .base import Generator
webui-docker-invoke-1  |   File "/InvokeAI/ldm/invoke/generator/base.py", line 21, in <module>
webui-docker-invoke-1  |     from pytorch_lightning import seed_everything
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/__init__.py", line 34, in <module>
webui-docker-invoke-1  |     from pytorch_lightning.callbacks import Callback  # noqa: E402
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/callbacks/__init__.py", line 25, in <module>
webui-docker-invoke-1  |     from pytorch_lightning.callbacks.progress import ProgressBarBase, RichProgressBar, TQDMProgressBar
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/callbacks/progress/__init__.py", line 22, in <module>
webui-docker-invoke-1  |     from pytorch_lightning.callbacks.progress.rich_progress import RichProgressBar  # noqa: F401
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/callbacks/progress/rich_progress.py", line 20, in <module>
webui-docker-invoke-1  |     from torchmetrics.utilities.imports import _compare_version
webui-docker-invoke-1  | ImportError: cannot import name '_compare_version' from 'torchmetrics.utilities.imports' (/opt/conda/lib/python3.10/site-packages/torchmetrics/utilities/imports.py)
```

**Which UI**

invoke

**Hardware / Software**

- OS: Linux Mint
- OS version: 21.1
- WSL version (if applicable): 
- Docker Version: 24.0.6
- Docker compose version: v2.21.0
- Repo version: master `6a34739135eb112667f00943c1fac98ab294716a`
- RAM: 48GB
- GPU/VRAM: nvidia 2060

**Steps to Reproduce**

`docker compose --profile download up --build`
`docker compose --profile invoke up --build`

**Additional context**

I already made a fresh clone and cleaned my docker containers (`docker system prune -a`). So this is a completely fresh build. 

Anyone run into this? Any pointers?

Over at invoke ai I found something about installing torchmetrics v0.11.4 (https://github.com/invoke-ai/InvokeAI/issues/3658). Is this something I can configure with an env var?

### LINKED ISSUE #598: ImportError: cannot import name 'url_quote' from 'werkzeug.urls'
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

**invoke**
try
```shell
sudo docker compose --profile invoke up --build
```
returned:
```shell
[+] Building 1.0s (17/17) FINISHED                                                                   docker:default
 => [invoke internal] load .dockerignore                                                                       0.0s
 => => transferring context: 2B                                                                                0.0s
 => [invoke internal] load build definition from Dockerfile                                                    0.0s
 => => transferring dockerfile: 2.37kB                                                                         0.0s
 => [invoke internal] load metadata for docker.io/pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime                0.7s
 => [invoke internal] load metadata for docker.io/library/alpine:3.17                                          1.0s
 => [invoke xformers 1/2] FROM docker.io/library/alpine:3.17@sha256:f71a5f071694a785e064f05fed657bf8277f1b211  0.0s
 => [invoke stage-1 1/9] FROM docker.io/pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime@sha256:82e0d379a5dedd63  0.0s
 => [invoke internal] load build context                                                                       0.0s
 => => transferring context: 96B                                                                               0.0s
 => CACHED [invoke stage-1 2/9] RUN --mount=type=cache,target=/var/cache/apt   apt-get update &&   apt-get in  0.0s
 => CACHED [invoke stage-1 3/9] RUN git clone https://github.com/invoke-ai/InvokeAI.git /InvokeAI              0.0s
 => CACHED [invoke stage-1 4/9] WORKDIR /InvokeAI                                                              0.0s
 => CACHED [invoke stage-1 5/9] RUN --mount=type=cache,target=/root/.cache/pip   git reset --hard f3b2e029219  0.0s
 => CACHED [invoke stage-1 6/9] RUN --mount=type=cache,target=/root/.cache/pip   git fetch &&   git reset --h  0.0s
 => CACHED [invoke stage-1 7/9] RUN --mount=type=cache,target=/root/.cache/pip   pip uninstall -y torchmetric  0.0s
 => CACHED [invoke xformers 2/2] COPY wheel.whl /                                                              0.0s
 => CACHED [invoke stage-1 8/9] RUN --mount=type=cache,target=/root/.cache/pip   --mount=type=bind,from=xform  0.0s
 => CACHED [invoke stage-1 9/9] COPY . /docker/                                                                0.0s
 => [invoke] exporting to image                                                                                0.0s
 => => exporting layers                                                                                        0.0s
 => => writing image sha256:72c3dd3cfae48404e4994df16cd85fc6d5aa5707956a7388c023146f00511906                   0.0s
 => => naming to docker.io/library/sd-invoke:30                                                                0.0s
[+] Running 1/0
 ✔ Container webui-docker-invoke-1  Created                                                                    0.0s 
Attaching to webui-docker-invoke-1
webui-docker-invoke-1  | Mounted ldm
webui-docker-invoke-1  | Mounted .cache
webui-docker-invoke-1  | Mounted RealESRGAN
webui-docker-invoke-1  | Mounted Codeformer
webui-docker-invoke-1  | Mounted GFPGAN
webui-docker-invoke-1  | Mounted GFPGANv1.4.pth
webui-docker-invoke-1  | Loading Python libraries...
webui-docker-invoke-1  | 
webui-docker-invoke-1  | * Initializing, be patient...
webui-docker-invoke-1  | >> Initialization file /InvokeAI/invokeai.init found. Loading...
webui-docker-invoke-1  | 
webui-docker-invoke-1  | ** DOWNLOADING SUPPORT MODELS **
webui-docker-invoke-1  | Installing bert tokenizer...
webui-docker-invoke-1  | Installing SD1 clip model...
webui-docker-invoke-1  | Installing SD2 clip model...
webui-docker-invoke-1  | Installing models from RealESRGAN...
webui-docker-invoke-1  | Installing RealESRGAN model file https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.5.0/realesr-general-x4v3.pth......exists
webui-docker-invoke-1  | Installing RealESRGANwdn model file https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.5.0/realesr-general-wdn-x4v3.pth......exists
webui-docker-invoke-1  | Installing GFPGAN models...
webui-docker-invoke-1  | Installing GFPGAN weights model file https://github.com/TencentARC/GFPGAN/releases/download/v1.3.0/GFPGANv1.4.pth......exists
webui-docker-invoke-1  | Installing GFPGAN weights model file https://github.com/xinntao/facexlib/releases/download/v0.1.0/detection_Resnet50_Final.pth......exists
webui-docker-invoke-1  | Installing GFPGAN weights model file https://github.com/xinntao/facexlib/releases/download/v0.2.2/parsing_parsenet.pth......exists
webui-docker-invoke-1  | Installing CodeFormer model file...
webui-docker-invoke-1  | Installing CodeFormer model file https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/codeformer.pth......exists
webui-docker-invoke-1  | Installing clipseg model for text-based masking...
webui-docker-invoke-1  | Installing model for NSFW content detection...
webui-docker-invoke-1  | AutoFeatureExtractor...
webui-docker-invoke-1  | StableDiffusionSafetyChecker...
webui-docker-invoke-1  | Installing stabilityai VAE...
webui-docker-invoke-1  | * vae-ft-mse-840000-ema-pruned.ckpt: complete file found. Skipping.
webui-docker-invoke-1  | 
webui-docker-invoke-1  | ** DOWNLOADING DIFFUSION WEIGHTS **
webui-docker-invoke-1  | == INSTALLING SELECTED STARTER MODELS ==
webui-docker-invoke-1  | Downloading stable-diffusion-1.5:
webui-docker-invoke-1  | Downloading sd-inpainting-1.5:
webui-docker-invoke-1  | Downloading stable-diffusion-2.1-768:
webui-docker-invoke-1  | ** models.yaml exists. Renaming to models.yaml.orig
webui-docker-invoke-1  | Successfully created new configuration file /InvokeAI/configs/models.yaml
webui-docker-invoke-1  | 
webui-docker-invoke-1  | ** INVOKEAI INSTALLATION SUCCESSFUL **
webui-docker-invoke-1  | If you installed manually from source or with 'pip install': activate the virtual environment
webui-docker-invoke-1  | then run one of the following commands to start InvokeAI.
webui-docker-invoke-1  | 
webui-docker-invoke-1  | Web UI:
webui-docker-invoke-1  |    invokeai --web # (connect to http://localhost:9090)
webui-docker-invoke-1  |    invokeai --web --host 0.0.0.0 # (connect to http://your-lan-ip:9090 from another computer on the local network)
webui-docker-invoke-1  | 
webui-docker-invoke-1  | Command-line interface:
webui-docker-invoke-1  |    invokeai
webui-docker-invoke-1  | 
webui-docker-invoke-1  | If you installed using an installation script, run:
webui-docker-invoke-1  |   /InvokeAI/invoke.sh
webui-docker-invoke-1  | 
webui-docker-invoke-1  | Add the '--help' argument to see all of the command-line switches available for use.
webui-docker-invoke-1  | 
webui-docker-invoke-1  | * Initializing, be patient...
webui-docker-invoke-1  | >> Initialization file /InvokeAI/invokeai.init found. Loading...
webui-docker-invoke-1  | >> Internet connectivity is True
webui-docker-invoke-1  | >> InvokeAI, version 2.3.5.post2
webui-docker-invoke-1  | >> InvokeAI runtime directory is "/InvokeAI"
webui-docker-invoke-1  | >> GFPGAN Initialized
webui-docker-invoke-1  | >> CodeFormer Initialized
webui-docker-invoke-1  | >> ESRGAN Initialized
webui-docker-invoke-1  | >> Using device_type cuda
webui-docker-invoke-1  | >> CUDA device 'NVIDIA A100 80GB PCIe' (GPU 0)
webui-docker-invoke-1  | >> xformers memory-efficient attention is available and enabled
webui-docker-invoke-1  | >> NSFW checker is disabled
webui-docker-invoke-1  | >> Current VRAM usage:  0.00G
webui-docker-invoke-1  | >> Loading diffusers model from runwayml/stable-diffusion-v1-5
webui-docker-invoke-1  |    | Using faster float16 precision
webui-docker-invoke-1  |    | Loading diffusers VAE from stabilityai/sd-vae-ft-mse
webui-docker-invoke-1  |    | Default image dimensions = 512 x 512
webui-docker-invoke-1  | >> Model loaded in 7.70s
webui-docker-invoke-1  | >> Max VRAM used to load the model: 2.16G 
webui-docker-invoke-1  | >> Current VRAM usage:2.16G
webui-docker-invoke-1  | >> Loading embeddings from /data/embeddings/
webui-docker-invoke-1  | >> Textual inversion triggers: 
webui-docker-invoke-1  | >> Setting Sampler to k_lms (LMSDiscreteScheduler)
webui-docker-invoke-1  | 
webui-docker-invoke-1  | * --web was specified, starting web server...
webui-docker-invoke-1  | Traceback (most recent call last):
webui-docker-invoke-1  |   File "/opt/conda/bin/invokeai", line 8, in <module>
webui-docker-invoke-1  |     sys.exit(main())
webui-docker-invoke-1  |   File "/InvokeAI/ldm/invoke/CLI.py", line 184, in main
webui-docker-invoke-1  |     invoke_ai_web_server_loop(gen, gfpgan, codeformer, esrgan)
webui-docker-invoke-1  |   File "/InvokeAI/ldm/invoke/CLI.py", line 1078, in invoke_ai_web_server_loop
webui-docker-invoke-1  |     from invokeai.backend import InvokeAIWebServer
webui-docker-invoke-1  |   File "/InvokeAI/invokeai/backend/__init__.py", line 4, in <module>
webui-docker-invoke-1  |     from .invoke_ai_web_server import InvokeAIWebServer
webui-docker-invoke-1  |   File "/InvokeAI/invokeai/backend/invoke_ai_web_server.py", line 17, in <module>
webui-docker-invoke-1  |     from flask import Flask, redirect, send_from_directory, request, make_response
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/flask/__init__.py", line 7, in <module>
webui-docker-invoke-1  |     from .app import Flask as Flask
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/flask/app.py", line 27, in <module>
webui-docker-invoke-1  |     from . import cli
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/flask/cli.py", line 17, in <module>
webui-docker-invoke-1  |     from .helpers import get_debug_flag
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/flask/helpers.py", line 14, in <module>
webui-docker-invoke-1  |     from werkzeug.urls import url_quote
webui-docker-invoke-1  | ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/opt/conda/lib/python3.10/site-packages/werkzeug/urls.py)
webui-docker-invoke-1  | Exception ignored in atexit callback: <built-in function write_history_file>
webui-docker-invoke-1  | FileNotFoundError: [Errno 2] No such file or directory
webui-docker-invoke-1 exited with code 1
```
**Hardware / Software**

- OS: Ubuntu 22.04
- OS version: Ubuntu 22.04.3 LTS
- Docker Version:
 ```
  Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:44 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 ```
- Docker compose version: v2.21.0
- Repo version: 8.1.0-5-g6a34739
- RAM: 1TB
- GPU/VRAM: 
 ```
 NVIDIA A100 80G
 NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0
 ```

**Steps to Reproduce**
0. git clone this repo.
1. ```docker compose --profile download up --build``` succeeded.
2. models in /data were manually downloaded then.
3. ```docker compose --profile invoke up --build``` triggered this error.

### LINKED ISSUE #630: Failed to build invoke ui - get "ImportError" on "ModelSearchArguments"
**Has this issue been opened before?**

- [x ] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

On building with 
```
docker compose --profile invoke up --build
```
get the following:
image

**Which UI**

invoke

**Hardware / Software**

- OS: Ubuntu 22.04
- OS version: 22.04.3 LTS
- Docker Version: 24.0.7
- Docker compose version: 2.21.0

**Steps to Reproduce**
1. type: docker compose --profile invoke up --build
2. See error

### LINKED ISSUE #640: Error with auto and invoke: libnvidia-ml.so.1 (apparently missing)
```
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown
```

So, this is strange i get the same error with auto or invoke, but I download the original repo from AUTOMATIC11111 and build with python and it's working, the drivers and de toolkit are good:

```
nvidia-smi

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.146.02             Driver Version: 535.146.02   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060        Off | 00000000:01:00.0  On |                  N/A |
|  0%   34C    P8               6W / 170W |      1MiB / 12288MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

If I do a search: `sudo find / -name libnvidia-ml.so*`

```
/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
/usr/local/cuda-12.3/targets/x86_64-linux/lib/stubs/libnvidia-ml.so
```

So No idea at this point, the auto-CPU working good too.

**Hardware / Software**

- OS: [Ubuntu 22.04]
- OS version: Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-91-generic x86_64)
- WSL version (if applicable): Wsman Shell commandLine, version 0.2.1
- Docker Version: 24.0.7
- Docker compose version: v2.21.0
- Repo version: master
- RAM: 16GB
- GPU/VRAM: 12GB

**Steps to Reproduce**

docker compose --profile auto up --build

### PR DESCRIPTION
**Pull request by dinandmentink**
Closes issue #595 

I'm unsure what the procedure is to update the different backends. But upgrading invoke to version v3.2.2. works perfectly for me (see screenshot below) and fixes my issue.

image

### Update versions
- invoke: https://github.com/invoke-ai/InvokeAI/commit/dedead672f2e9f995b6b96d7ada37456dab15b55

### CODE REVIEW

**Comment by AbdBarho** [comment]
hey thank you, can you check that if you add any models from UI, would the configuration be saved when you restart the container?

**Comment by dinandmentink** [comment]
Sure, I could try that. I have never worked with installing models. Could you please point me to the easiest model to download and install?

**Comment by AbdBarho** [comment]
Hey sorry for being so late on this, life got in the way, I will comeback to this shortly.

**Comment by AbdBarho** [comment]
I pushed one commit, it seems that the new folder structure of invoke will force everyone to redownload all the models on start up, which is not what we want.

This will take more time.

**Comment by dinandmentink** [comment]
> Hey sorry for being so late on this, life got in the way, I will comeback to this shortly.

No worries, take care.

> I pushed one commit, it seems that the new folder structure of invoke will force everyone to redownload all the models on start up, which is not what we want.
>
> This will take more time.

Ok. I'll wait. For now I got it working locally (with redownloading all the models on startup, you're right). So I'm fine. Good luck!

**Comment by geekyouth** [comment]
```
webui-docker-invoke-1  | [2023-11-30 01:29:55,456]::[InvokeAI]::INFO --> Installing https://huggingface.co/embed/EasyNegative/resolve/main/EasyNegative.safetensors [3/11]
webui-docker-invoke-1  | [2023-11-30 01:29:57,022]::[InvokeAI]::INFO --> /InvokeAI/models/tmpxihpxo6l/EasyNegative.safetensors: Downloading...
/InvokeAI/models/tmpxihpxo6l/EasyNegative.safetensors: 100% 24.7k/24.7k [00:00<00:00, 308kiB/s]
webui-docker-invoke-1  | [2023-11-30 01:29:57,105]::[InvokeAI]::INFO --> Installing lllyasviel/control_v11f1p_sd15_depth [4/11]
webui-docker-invoke-1  | [2023-11-30 01:29:58,196]::[InvokeAI]::INFO --> config.json: Downloading...
config.json: 100% 945/945 [00:00<00:00, 1.18MiB/s]
webui-docker-invoke-1  | Traceback (most recent call last):
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
webui-docker-invoke-1  |     httplib_response = self._make_request(
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
webui-docker-invoke-1  |     self._validate_conn(conn)
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
webui-docker-invoke-1  |     conn.connect()
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
webui-docker-invoke-1  |     self.sock = ssl_wrap_socket(
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
webui-docker-invoke-1  |     ssl_sock = _ssl_wrap_socket_impl(
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
webui-docker-invoke-1  |     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/ssl.py", line 513, in wrap_socket
webui-docker-invoke-1  |     return self.sslsocket_class._create(
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/ssl.py", line 1071, in _create
webui-docker-invoke-1  |     self.do_handshake()
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/ssl.py", line 1342, in do_handshake
webui-docker-invoke-1  |     self._sslobj.do_handshake()
webui-docker-invoke-1  | ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1007)
webui-docker-invoke-1  | 
webui-docker-invoke-1  | During handling of the above exception, another exception occurred:
webui-docker-invoke-1  | 
webui-docker-invoke-1  | Traceback (most recent call last):
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
webui-docker-invoke-1  |     resp = conn.urlopen(
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
webui-docker-invoke-1  |     retries = retries.increment(
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
webui-docker-invoke-1  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
webui-docker-invoke-1  | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Max retries exceeded with url: /repos/87/db/87dbc35498cbc07f55b975cd38ac1e2482d8440ccae676328faabc0cf5c51c5d/999aca923ca5e19e70e6afc8d11073cc3c03553ca935b636bd5925df4a1c77d1?r
esponse-content-disposition=attachment%3B+filename*%3DUTF-8%27%27diffusion_pytorch_model.safetensors%3B+filename%3D%22diffusion_pytorch_model.safetensors%22%3B&Expires=1701566999&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwMTU2Njk5OX19LCJSZXNvdXJjZS
I6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9yZXBvcy84Ny9kYi84N2RiYzM1NDk4Y2JjMDdmNTViOTc1Y2QzOGFjMWUyNDgyZDg0NDBjY2FlNjc2MzI4ZmFhYmMwY2Y1YzUxYzVkLzk5OWFjYTkyM2NhNWUxOWU3MGU2YWZjOGQxMTA3M2NjM2MwMzU1M2NhOTM1YjYzNmJkNTkyNWRmNGExYzc3ZDE~cmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qIn1dfQ__&Signature=kCz
F1ayJKBqujkb1WFUl6EOEuRNXk~VQJAC6zNYqt0w8IsXvxPaABUMkk0U3AJU0qap2KcPetykLfrV0poh1QmAre1DqSmbPVHGXkwdyBPaLxpJ4-OWakfAqBa1-aJZNAKbFyNNUhQ9Ii6kCxcQsnUpIbZKHP9hTCp-FNpiG-Yhlys2r0-R4CQcHIaMPPdE6HDu6nRj4XUgUOsx3hJNt-MWCQReimCCt7a43Ziy0fwR3tDQOSGiUIMtDniv-MkQXr44w-Ru9Gyr09x8mBi-tg2hpF3~vxbtOqxZupAzln~z
n5EfaPXpXij3y0ErALsPsGC4gw6Y14z0Cn5uBQfLPgw__&Key-Pair-Id=KVTP0A1DKRTAX (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)')))
webui-docker-invoke-1  | 
webui-docker-invoke-1  | During handling of the above exception, another exception occurred:
webui-docker-invoke-1  | 
webui-docker-invoke-1  | Traceback (most recent call last):
webui-docker-invoke-1  |   File "/opt/conda/bin/invokeai-configure", line 8, in <module>
webui-docker-invoke-1  |     sys.exit(invokeai_configure())
webui-docker-invoke-1  |   File "/InvokeAI/invokeai/backend/install/invokeai_configure.py", line 943, in main
webui-docker-invoke-1  |     process_and_execute(opt, models_to_download)
webui-docker-invoke-1  |   File "/InvokeAI/invokeai/frontend/install/model_install.py", line 689, in process_and_execute
webui-docker-invoke-1  |     installer.install(selections)
webui-docker-invoke-1  |   File "/InvokeAI/invokeai/backend/install/model_install_backend.py", line 217, in install
webui-docker-invoke-1  |     self.heuristic_import(path)
webui-docker-invoke-1  |   File "/InvokeAI/invokeai/backend/install/model_install_backend.py", line 262, in heuristic_import
webui-docker-invoke-1  |     models_installed.update({str(model_path_id_or_url): self._install_repo(str(model_path_id_or_url))})
webui-docker-invoke-1  |   File "/InvokeAI/invokeai/backend/install/model_install_backend.py", line 364, in _install_repo
webui-docker-invoke-1  |     location = self._download_hf_model(repo_id, files, staging, subfolder=subfolder)
webui-docker-invoke-1  |   File "/InvokeAI/invokeai/backend/install/model_install_backend.py", line 506, in _download_hf_model
webui-docker-invoke-1  |     p = hf_download_with_resume(
webui-docker-invoke-1  |   File "/InvokeAI/invokeai/backend/install/model_install_backend.py", line 575, in hf_download_with_resume
webui-docker-invoke-1  |     resp = requests.get(url, headers=header, stream=True)
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/requests/api.py", line 73, in get
webui-docker-invoke-1  |     return request("get", url, params=params, **kwargs)
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/requests/api.py", line 59, in request
webui-docker-invoke-1  |     return session.request(method=method, url=url, **kwargs)
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
webui-docker-invoke-1  |     resp = self.send(prep, **send_kwargs)
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 723, in send
webui-docker-invoke-1  |     history = [resp for resp in gen]
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 723, in <listcomp>
webui-docker-invoke-1  |     history = [resp for resp in gen]
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 266, in resolve_redirects
webui-docker-invoke-1  |     resp = self.send(
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
webui-docker-invoke-1  |     r = adapter.send(request, **kwargs)
webui-docker-invoke-1  |   File "/opt/conda/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
webui-docker-invoke-1  |     raise SSLError(e, request=request)
webui-docker-invoke-1  | requests.exceptions.SSLError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Max retries exceeded with url: /repos/87/db/87dbc35498cbc07f55b975cd38ac1e2482d8440ccae676328faabc0cf5c51c5d/999aca923ca5e19e70e6afc8d11073cc3c03553ca935b636bd5925df4a1c77d1?respo
nse-content-disposition=attachment%3B+filename*%3DUTF-8%27%27diffusion_pytorch_model.safetensors%3B+filename%3D%22diffusion_pytorch_model.safetensors%22%3B&Expires=1701566999&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwMTU2Njk5OX19LCJSZXNvdXJjZSI6Im
h0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9yZXBvcy84Ny9kYi84N2RiYzM1NDk4Y2JjMDdmNTViOTc1Y2QzOGFjMWUyNDgyZDg0NDBjY2FlNjc2MzI4ZmFhYmMwY2Y1YzUxYzVkLzk5OWFjYTkyM2NhNWUxOWU3MGU2YWZjOGQxMTA3M2NjM2MwMzU1M2NhOTM1YjYzNmJkNTkyNWRmNGExYzc3ZDE~cmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qIn1dfQ__&Signature=kCzF1ay
JKBqujkb1WFUl6EOEuRNXk~VQJAC6zNYqt0w8IsXvxPaABUMkk0U3AJU0qap2KcPetykLfrV0poh1QmAre1DqSmbPVHGXkwdyBPaLxpJ4-OWakfAqBa1-aJZNAKbFyNNUhQ9Ii6kCxcQsnUpIbZKHP9hTCp-FNpiG-Yhlys2r0-R4CQcHIaMPPdE6HDu6nRj4XUgUOsx3hJNt-MWCQReimCCt7a43Ziy0fwR3tDQOSGiUIMtDniv-MkQXr44w-Ru9Gyr09x8mBi-tg2hpF3~vxbtOqxZupAzln~zn5Ef
aPXpXij3y0ErALsPsGC4gw6Y14z0Cn5uBQfLPgw__&Key-Pair-Id=KVTP0A1DKRTAX (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)')))
webui-docker-invoke-1  | /opt/conda/lib/python3.10/tempfile.py:860: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmp96tqve9v'>
webui-docker-invoke-1  |   _warnings.warn(warn_message, ResourceWarning)
webui-docker-invoke-1 exited with code 1
root@KELL-PC:/mnt/d/.algolaser/.code/.docker/stable-diffusion-webui-docker# 

```

**Comment by dakyskye** [comment]
Still waiting for #595 to close

**Pull request closed without merging**
