### PR TITLE
Update Auto v1.9.3

### PR DESCRIPTION
**Pull request by SachiaLanlus**
Closes issue  #672

### Update versions

- auto: https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases/tag/v1.8.0

### CODE REVIEW

**Comment by mashb1t** [comment]
LOL, i'm working on exactly this PR right now! Thanks a lot, no issues, works perfectly fine.

@AbdBarho thank you for reviewing!

**Comment by SachiaLanlus** [comment]
> please check this one out and update

Auto still using the 0.0.23.post1.
Do you think we would be better to follow their favor or upgrade the newer as possible?
https://github.com/AUTOMATIC1111/stable-diffusion-webui/compare/v1.7.0...v1.8.0#diff-b8454e8123e62f9ec2c0d4e299e0690c27592af4230a16976ecd4745e61871e7R343

**Comment by mashb1t** [comment]
Thanks for the feedback. Let's stick with their package versions to mirror them.

**Comment by darkvertex** [comment]
Out of curiosity what is the reason for removing the CodeFormer lines? Is it part of Auto now?

**Comment by SachiaLanlus** [comment]
v1.9.0 is more like a chore fix.
There are lots of naming convention and code style change.
But the module dependencies do not change so just replace reference with newer tag and rebuild.

**Review by DevilaN — APPROVED** [review]
Works as intended.

**Comment by picarica** [comment]
is this repo abondoned no activity nothing is being pulled

**Comment by mashb1t** [comment]
@AbdBarho what's the next step in this matter?

**Comment by DevilaN** [comment]
Probably somebody should just take over with fork and continue work.
The problem with this repo is that it tries to integrate many different UIs. It would be easier to split the work and focus solely on one UI. I could maintain A1111 as I use it on regular basis, but this changes nothing for this very repository :(

**Review by AbdBarho — APPROVED** [review]
@SachiaLanlus thank you very much for this! and sorry for being late.

@DevilaN I plan to split for the maintenance like you said.

**Pull request merged**
