### PR TITLE
fix: comfyui manager download path

### PR DESCRIPTION
**Pull request by nzlov**
Fix `comfyui manager` not downloading to export directory

### CODE REVIEW

**Review by Artibex — APPROVED** [review]
I hade a issue with installing custom nodes. This fixed it.

**Comment by 66li** [comment]
Wouldn't it be better to have a separate directory for checkpoints?

**Comment by 66li** [comment]
> Wouldn't it be better to have a separate directory for checkpoints?

And config.

**Comment by 66li** [comment]
https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/master/services/comfy/extra_model_paths.yaml
It seems to be controlled by this

**Comment by GinIsTheAnswer** [comment]
> https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/master/services/comfy/extra_model_paths.yaml It seems to be controlled by this

Does that file even do anything? It gets copied (twice), but the entrypoint doesn't use it?

**Comment by AbdBarho** [comment]
Hey, sorry for being late on this, I did an update in #603, maybe this has an effect or fixes the issue.

I am planning on simplifying the entire mount structure for all UIs since they are making it very hard to maintain, so maybe your problem could also be solved by this refactoring.

https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/master/services/comfy/extra_model_paths.yaml
This is file is loaded by the comfy UI to know where to look for the model files.

**Comment by RyzeNGrind** [comment]
Hey I was also looking for some documentation to understand how the models, config, extensions can be saved to be used by the 3 UIs as much as possible. Instead of having separate paths specified to each interface.

**Comment by AbdBarho** [comment]
Hey @RyzeNGrind, I understand that you want to share models between the UIs as much as possible.

Unfortunately, it is causing a noticeable maintenance overhead on my side to keep everything aligned, especially since I don't maintain any of the 3 UIs and stuff keeps changing underneath.

I want to do some poll to understand what the users want / need to decide on the future structure.

**Pull request closed without merging**
