### PR TITLE
Alpha support  for sd v2.x in auto

### PR DESCRIPTION
**Pull request by AbdBarho**
https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/44c46f0ed395967cd3830dd481a2db759fda5b3b

Install sd 2 from [these instructions](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#stable-diffusion-20), put the downloaded files in `data/StableDiffusion/`, maybe create a subfolder `v2` and put the models in it, just to keep everything clean.

There will be problems, so be warry.

### CODE REVIEW

**Comment by AbdBarho** [comment]
@ProducerMatt yes I am still working on it.

You also need the corresponding yaml file from https://github.com/Stability-AI/stablediffusion/tree/main/configs/stable-diffusion, rename to model file name

**Comment by ProducerMatt** [comment]
I understand, there's plenty of kinks to work out over the next few weeks before having feature parity. 🙂 I'll help whenever I can.

Oh yeah, the YAML files. I downloaded them but forgot to actually put them in. 😬 Now I get the following error:

```
Loading config from: /stable-diffusion-webui/models/Stable-diffusion/sd2/768-v-ema.yaml
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gradio/routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 982, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 824, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/stable-diffusion-webui/modules/ui.py", line 1664, in <lambda>
    fn=lambda value, k=k: run_settings_single(value, key=k),
  File "/stable-diffusion-webui/modules/ui.py", line 1505, in run_settings_single
    if not opts.set(key, value):
  File "/stable-diffusion-webui/modules/shared.py", line 454, in set
    self.data_labels[key].onchange()
  File "/stable-diffusion-webui/webui.py", line 44, in f
    res = func(*args, **kwargs)
  File "/stable-diffusion-webui/webui.py", line 86, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: modules.sd_models.reload_model_weights()))
  File "/stable-diffusion-webui/modules/sd_models.py", line 279, in reload_model_weights
    load_model(checkpoint_info)
  File "/stable-diffusion-webui/modules/sd_models.py", line 247, in load_model
    sd_model = instantiate_from_config(sd_config.model)
  File "/stable-diffusion-webui/repositories/stable-diffusion/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/stable-diffusion-webui/repositories/stable-diffusion/ldm/models/diffusion/ddpm.py", line 448, in __init__
    super().__init__(conditioning_key=conditioning_key, *args, **kwargs)
  File "/stable-diffusion-webui/repositories/stable-diffusion/ldm/models/diffusion/ddpm.py", line 76, in __init__
    assert parameterization in ["eps", "x0"], 'currently only supporting "eps" and "x0"'
  AssertionError: currently only supporting "eps" and "x0"
```

**Comment by AbdBarho** [comment]
@ProducerMatt are you sure you are running the code from this branch?

the folder `/stable-diffusion-webui/repositories/stable-diffusion/` should not exist.

**Comment by ProducerMatt** [comment]
Sorry, disregard that. I merged this branch with my deforum changes, so I must have merged them wrong. I'll be sure to test on the non-modified version first.

**Pull request merged**
