### PR TITLE
wget is needed for gdown

### PR DESCRIPTION
**Pull request by redthing1**

### CODE REVIEW

**Comment by AbdBarho** [comment]
@redthing1  since when?

**Comment by redthing1** [comment]
> @redthing1 since when?

Run docker-compose up auto-cpu, gdown will fail because it needs wget

**Comment by AbdBarho** [comment]
I have just tried it with no problems:

```
#10 [xformers 2/4] RUN pip install gdown
#10 CACHED

#13 [xformers 3/4] RUN echo hi
#0 0.473 hi
#0 0.473 + echo hi
#13 DONE 0.5s

#14 [xformers 4/4] RUN gdown https://drive.google.com/uc?id=1SqwicrLx1TrG_sbbEoIF_3TUHd4EYSmw -O /wheel.whl
#14 0.673 + gdown 'https://drive.google.com/uc?id=1SqwicrLx1TrG_sbbEoIF_3TUHd4EYSmw' -O /wheel.whl
#14 3.807 Downloading...
#14 3.807 From: https://drive.google.com/uc?id=1SqwicrLx1TrG_sbbEoIF_3TUHd4EYSmw
#14 3.807 To: /wheel.whl
100%|██████████| 21.0M/21.0M [00:02<00:00, 9.73MB/s]
#14 DONE 6.2s
```

I assume you have an old version of `python:3.10-slim`, can you try pulling the latest version `docker pull python:3.10-slim` and then running without installing `wget`?

This might be an indicator that we have to better pin the versions of images used.

**Comment by redthing1** [comment]
That worked. Oops. Thank you for help.

**Pull request closed without merging**
