### PR TITLE
mount styles.csv for auto

### PR DESCRIPTION
**Pull request by wallopthecat**
persists styles saved with auto's ui - previous to this change, the saved styles were lost on container rebuild

### CODE REVIEW

**Comment by AbdBarho** [comment]
I will try changing the contribution configuration so that users don't miss the info about creating an issue.

Anyway, this will crash if the styles.csv does not exist in the config folder.

**Comment by wallopthecat** [comment]
Oops, sorry I missed that. Do you need me to fix anything or want me to close this?

**Comment by AbdBarho** [comment]
@wallopthecat no problem, I need you to fix this:

> this will crash if the styles.csv does not exist in the config folder.

create an empty file if it does not exist, see how I did it for the config json

**Comment by wallopthecat** [comment]
> create an empty file if it does not exist
Added this change ^ and verified the defaults from my file and here https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/2fd7935ef4ed296db5dfd8c7fea99244816f8cf0/modules/styles.py#L42

**Comment by AbdBarho** [comment]
@wallopthecat thank you, unfortunately, it does not seem to work, while the file definitely is created when booting up, if add styles, they are not saved to the disk, if I open `data/config/auto/styles.csv` it remains the same. Meaning the styles are lost on restart.

**Comment by wallopthecat** [comment]
Thanks, will do some digging

**Comment by wallopthecat** [comment]
It doesn't seem to be symlinked properly, butthe other files are. Will take a deeper look later 
output of `ls -la` in `/stable-diffusion-webui`
image

**Pull request closed without merging**
