### PR TITLE
.env override for docker-compose.yml

### PR DESCRIPTION
**Pull request by wookiefriseur**
What do you think of this?

1. easy override without touching any YAMLs
2. local update to latest versions without merging (for people with custom settings)
3. no duplicates with settings that have arrays 
    - when I use `docker-override.yml`, it for instance binds ports from both ymls

Example: 
- `"${HOST_PORT:-7860}:7860"` - setting in `docker-compose.yml`
- `HOST_PORT=12345` - override in `.env`

### CODE REVIEW

**Comment by wookiefriseur** [comment]
Oh, the draft wasn't supposed to start your Actions, sorry. Hope it's free

**Comment by AbdBarho** [comment]
Thank you.

Most of the stuff could actually be configured with `docker-compose.override.yml`, which is the recommended way, without the need of an `.env` file.

There is a discussion for the overriding the ports, because this is not possible per default. https://github.com/AbdBarho/stable-diffusion-webui-docker/discussions/430

I would prefer to keep the changes limited to the port, with one value for all UIs.

> Oh, the draft wasn't supposed to start your Actions, sorry. Hope it's free

Oh yeah it is all free!

**Comment by wookiefriseur** [comment]
Thanks, didn't see the discussion. Will continue there. You can close or use this PR if you want.

**Comment by LEv145** [comment]
I think it's better to add `WEBUI_PORT` and `WEBUI_ARGS` for each service, because `WEBUI_ARGS` for all services is different, as is the port if you use more than one service at the same time
I use several services with different ports, I have not experienced any problems

**Comment by AbdBarho** [comment]
I have added a minimal solution #521, which should be enough, I don't believe we need a high level of very granular customizability through the env file, a docker compose override should help you get most of the way there.

**Comment by wookiefriseur** [comment]
> I think it's better to add `WEBUI_PORT` and `WEBUI_ARGS` for each service, because `WEBUI_ARGS` for all services is different, as is the port if you use more than one service at the same time

I had it like that at first, but when services change you would have to keep track of the names. Right now you can have multiple `.env` files and load them on demand like so:

1. `docker compose --env-file .env-auto --profile auto up`
2. `docker compose --env-file .env-comfy --profile comfy up`
3. and so on ...

I use that for switching between profiles with my custom settings. I don't have the resources to run multiple profiles at the same time so I did not test that use case.

> I have added a minimal solution #521, which should be enough, I don't believe we need a high level of very granular customizability through the env file, a docker compose override should help you get most of the way there.

That's an OK solution for now, removing the multiple port problem. Good enough for my use cases. 👍 
People with multiple profiles can use a mix of custom `.env` files for the port and `docker-compose.override.yml` for the rest.

Let's just hope docker compose gets a patch to make the override more useful. The latest release does not seem to do what we need: https://github.com/AbdBarho/stable-diffusion-webui-docker/discussions/430#discussioncomment-6273565

**Comment by AbdBarho** [comment]
I will close this PR now, thank you for contributing, if we want to add this in the future I will reach out to you again.

**Pull request closed without merging**
