### PR TITLE
Docker compose override example file + .gitignore update

### LINKED ISSUE #101: [Feature request] Allow overriding docker-compose.yml
Docker compose allows using `docker-compose.override.yml` file for storing changes to service definitions in base `docker-compose.yml` file.
Having this allow us to continue using unmodified `docker-compose.yml` file in local copy of repository and do not bother about conflicts / not updating file when doing `git pull` on regular basis, as specific modifications are being made in `docker-compose.override.yml` file that should be not managed by git. Therefore it would be perfect if `docker-compose.override.yml` file was added to `.gitignore` so it will not pop up during `git status` command as untracked.
Also it would be nice if there was example override file distributed inside repository (`docker-compose.override.yml-dist` file) as a starter point for anybody who might want to set extra environment variables and other service tweaks without worrying about creating entire file from scratch.

I suppose, that this method should be described in README / wiki in setup & usage sections (as this is a good method to add / change CLI arguments for specific service.

### PR DESCRIPTION
**Pull request by DevilaN**
Docker compose allows override some settings in `docker-compose.yml` by using additional file: `docker-compose.override.yml`.
This allows to hold own settings in override file which does not conflict with updates made by pulling newer version with "git pull" command.

This feature requires three things:
1. Creating `docker-compose.override.yml-dist` file which is a distributed file inside repo. This file can be copied as `docker-compose.override.yml` and modified for own needs.
2. Change in `.gitignore` file so `docker-compose.override.yml` file is ignored, so git pull / commit will not complain about this file.
3. Modify wiki entry about setup to mention possibility to use this method.

Closes #101

### CODE REVIEW

**Comment by AbdBarho** [comment]
Thank you for wanting to contribute! you should have created an issue first before creating the merge request, as stated in [the readme](https://github.com/AbdBarho/stable-diffusion-webui-docker#contributing)

My biggest question would be: is this something we should provide? or something the end users can setup on their own? I totally agree with the wiki update with using the override file, I am not sure if we have to ship it in the repo.

My concern are breaking changes, if the user has some outdated config in their override file, we will have problems.

Also, non of this träfik is required, it only makes stuff less clear.

**Comment by DevilaN** [comment]
OK, my bad.
Most of time I am working with git outside of github, so pardon me please.

I'll create issue for discussion purposes then.

**Review by AbdBarho — CHANGES_REQUESTED** [review]
please remove the `docker-compose.override.yml-dist` file, I will update the wiki accordingly

**Comment by DevilaN** [comment]
File removed

**Review by AbdBarho — APPROVED** [review]
Thank you! I updated the usage page in the wiki

**Pull request merged**
