### PR TITLE
Update entrypoint.sh: Add Lora directory.

### PR DESCRIPTION
**Pull request by repligator**
Add Lora directory

### CODE REVIEW

**Comment by AbdBarho** [comment]
@repligator thank you, can you show me where Lora is documented in A1111? maybe there is something else that we need to include beside the folder mount.

**Comment by repligator** [comment]
I'm embarrassed to say that I don't know where or even if it is documented. The first thing I did was try (and fail) to find the documentation. Then I just added the directory on my own server, confirmed that it appeared in the UI, and submitted the pull request.

**Comment by AbdBarho** [comment]
@repligator I think I found it: https://github.com/AUTOMATIC1111/stable-diffusion-webui/tree/master/extensions-builtin

Not documented much, other than this:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/7b1c7ba87b14da9960d0347269421233f4cb5838/README.md?plain=1#L80

Could you please add the lora folder to `.gitignore`, then we can merge.

**Comment by repligator** [comment]
Done. Sorry, I accidentally did it via a second pull request. I'm not used to Git.

**Comment by AbdBarho** [comment]
Will merge in #306

**Pull request closed without merging**
