### PR TITLE
Support styles.csv in AUTOMATIC1111

### PR DESCRIPTION
**Pull request by gmasil**
I noticed that adding styles in AUTOMATIC1111 web UI is not persisted to host fs.

I added a simple example `styles.csv` containing some common negative expressions and added a mount in `docker-compose.yml`.
A default file must be present as the mount will cause problems when the file is missing all together.

2023-04-03 15_39_26-docker-compose yml - stable-diffusion-webui-docker - Visual Studio Code

My hopefully sane default negatives are
```
easynegative, ng_deepnegative_v1_75t, bad-hands-5, (worst quality, low quality:1.3), logo, watermark, text
```
but I am open for any suggestions, I just wanted to add something as an example.

I also added `styles.csv` to `.gitignore` file, as changes will be made by users which should not be upstreamed into the repository.

### CODE REVIEW

**Comment by gmasil** [comment]
I tested it, but it doesn't work. Just as you already discovered the changes are not written back into the host file. The file `styles.csv` is moved to `styles.csv.bak` before writing the new one.

After clean container startup:
```
lrwxrwxrwx 1 root root   28 Apr  3 15:49 styles.csv -> /data/config/auto/styles.csv
```

After saving a style:
```
-rw------- 1 root root   57 Apr  3 15:50 styles.csv
lrwxrwxrwx 1 root root   28 Apr  3 15:49 styles.csv.bak -> /data/config/auto/styles.csv
```

File contents of styles.csv:
```
name,prompt,negative_prompt
None,,
teststyle,,test
```

File contents of styles.csv.bak:
```
name,prompt,negative_prompt
None,,
```

So symlinking won't work.

Interestingly my solution isn't working as well. I thought: **why would my solution work then?**
I was pretty sure I could save a style, but I just checked it and I get the following expected error:

```
OSError: [Errno 16] Device or resource busy: '/stable-diffusion-webui/styles.csv' -> '/stable-diffusion-webui/styles.csv.bak'
```

So I guess we had to mount a folder in order to make that work. I will take a look into AUTOMATIC1111's repo to see if we can find a simpler solution on their side, possible by adding a flag to disable this backup strategy.

I'll come back to you in a couple of days.

**Comment by AbdBarho** [comment]
Thank you for your investigation, please don't invest too much time into this, in my book it is a 'nice to have'.

**Comment by gmasil** [comment]
I proposed a _solution_ at AUTOMATIC1111's repo. I really appreciate the functionality to quickly save some snippets. I am going to use my changes as of now, hopefully we can merge it into the repos.
I don't want to bother you with any of your time, that's why I am investing a little bit into it, so you don't have to :)

**Comment by gmasil** [comment]
Here is my temporary patch on how I use it personally in case anyone wants to copy it until we have sorted things out correctly:
https://github.com/gmasil/stable-diffusion-webui-docker/commit/90f0b1a8e4f64890a7c05a80f752245f820edede

```bash
wget https://github.com/gmasil/stable-diffusion-webui-docker/commit/90f0b1a8e4f64890a7c05a80f752245f820edede.patch
git apply 90f0b1a8e4f64890a7c05a80f752245f820edede.patch
```

**Comment by Renari** [comment]
I was able to get this working with only:
```
MOUNTS["${ROOT}/styles.csv"]="/data/styles.csv"
```
However I did extract a premade styles.csv to my `/data` mounted via a host path prior to making this change.

**Comment by gmasil** [comment]
Are you sure that you can save new styles from webui? Is it really persisted to your host file?

**Comment by Renari** [comment]
The styles.csv saved externally is read and loaded correctly, however it seems saving new styles will overwrite the symlink instead of following it, thus preventing the new additions.

**Comment by gmasil** [comment]
I see that there is little interest in this feature, so I am going to close this PR for now.
Maybe I come back when we resolved this: https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/9334
I don't see an elegant way to solve this here.

**Comment by LEv145** [comment]
Merged
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/9334

**Comment by LEv145** [comment]
@gmasil @AbdBarho 
Merged
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/9334

**Comment by gmasil** [comment]
@LEv145 it has been merged to dev, that means we still have to wait until it is merged to master and then we have to check what we have to do to use the latest revision as there are a lot of changes.

**Comment by LEv145** [comment]
> @LEv145 it has been merged to dev, that means we still have to wait until it is merged to master and then we have to check what we have to do to use the latest revision as there are a lot of changes.
Merged to master!

**Comment by AbdBarho** [comment]
Nice! I will wait a day or two for emergency bug fixes and then try to update. The last version was so buggy I did not dare to merge it #379

**Comment by gmasil** [comment]
And it doesn't count as a contribution when its merged to dev first :P
I used the dev branch for a couple of days (without docker) and that worked fine. Haven't had time to look into it using docker, maybe in the next days.

**Comment by AbdBarho** [comment]
@gmasil thank you for the PR in the upstream, adding this feature is now very easy #440

**Pull request closed without merging**
