### PR TITLE
Adds the ControlNet directory to gitignore

### PR DESCRIPTION
**Pull request by repligator**
Closes issue #

### Update versions

- auto: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/
- sygil: https://github.com/Sygil-Dev/sygil-webui/commit/
- invoke: https://github.com/invoke-ai/InvokeAI/commit/

### CODE REVIEW

**Review by repligator — COMMENTED** [review]
Adds the ControlNet directory to gitignore, which is used by several extensions.

**Comment by AbdBarho** [comment]
@repligator thank you, could you tell me which extensions require this folder? maybe I can do more changes to make the repo more compatible.

**Comment by repligator** [comment]
[https://github.com/Mikubill/sd-webui-controlnet](url)
There are also other several extensions that extend that extension (for want of a better term), such as [https://github.com/fkunn1326/openpose-editor](url) . Looking at things from a long term perspective, there are quite a few extensions that seem to want own directory inside Models. Would it be practical (or even possible) to ignore everything in Models except any directories that shouldn't be ignored?

**Comment by AbdBarho** [comment]
I see your point.

To be fully honest, I want to completely restructure this repository, and maybe make it easier to install & extend, I can't find the time to do it.

**Comment by gmasil** [comment]
This is now already done in https://github.com/AbdBarho/stable-diffusion-webui-docker/pull/385

**Pull request closed without merging**
