### PR TITLE
Update open_clip to v2.20.0 in Auto

### LINKED ISSUE #615: Loading SDXL 1.0 fails with RuntimeError: Model config for ViT-bigG-14 not found.
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

The commit 3e67f559d43b53faeb4a32b63c8b89391f0b7248 breaks loading of [SD XL - v1.0 VAE fix](https://civitai.com/models/101055/sd-xl) from civitai and [SD XL 1.0 base](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0) from huggingface.

```
$ docker compose --profile auto up --build
[+] Building 0.6s (24/24) FINISHED                                                                                                                            docker:default
 => [auto internal] load .dockerignore                                                                                                                                  0.0s
 => => transferring context: 2B                                                                                                                                         0.0s
 => [auto internal] load build definition from Dockerfile                                                                                                               0.0s
 => => transferring dockerfile: 2.70kB                                                                                                                                  0.0s
 => [auto internal] load metadata for docker.io/pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime                                                                           0.5s
 => [auto internal] load metadata for docker.io/alpine/git:2.36.2                                                                                                       0.0s
 => [auto internal] load build context                                                                                                                                  0.0s
 => => transferring context: 122B                                                                                                                                       0.0s
 => [auto stage-1  1/11] FROM docker.io/pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime@sha256:e4aaefef0c96318759160ff971b527ae61ee306a1204c5f6e907c4b45f05b8a3           0.0s
 => [auto download 1/8] FROM docker.io/alpine/git:2.36.2                                                                                                                0.0s
 => CACHED [auto stage-1  2/11] RUN --mount=type=cache,target=/var/cache/apt   apt-get update &&   apt-get install -y fonts-dejavu-core rsync git jq moreutils aria2    0.0s
 => CACHED [auto stage-1  3/11] RUN --mount=type=cache,target=/root/.cache/pip   git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git &&   cd stable-  0.0s
 => CACHED [auto download 2/8] COPY clone.sh /clone.sh                                                                                                                  0.0s
 => CACHED [auto download 3/8] RUN . /clone.sh stable-diffusion-stability-ai https://github.com/Stability-AI/stablediffusion.git cf1d67a6fd5ea1aa600c4df58e5b47da45f6b  0.0s
 => CACHED [auto download 4/8] RUN . /clone.sh CodeFormer https://github.com/sczhou/CodeFormer.git c5b4593074ba6214284d6acd5f1719b6c5d739af   && rm -rf assets inputs   0.0s
 => CACHED [auto download 5/8] RUN . /clone.sh BLIP https://github.com/salesforce/BLIP.git 48211a1594f1321b00f14c9f7a5b4813144b2fb9                                     0.0s
 => CACHED [auto download 6/8] RUN . /clone.sh k-diffusion https://github.com/crowsonkb/k-diffusion.git ab527a9a6d347f364e3d185ba6d714e22d80cb3c                        0.0s
 => CACHED [auto download 7/8] RUN . /clone.sh clip-interrogator https://github.com/pharmapsychotic/clip-interrogator 2cf03aaf6e704197fd0dae7c7f96aa59cf1b11c9          0.0s
 => CACHED [auto download 8/8] RUN . /clone.sh generative-models https://github.com/Stability-AI/generative-models 45c443b316737a4ab6e40413d7794a7f5657c19f             0.0s
 => CACHED [auto stage-1  4/11] COPY --from=download /repositories/ /stable-diffusion-webui/repositories/                                                               0.0s
 => CACHED [auto stage-1  5/11] RUN mkdir /stable-diffusion-webui/interrogate && cp /stable-diffusion-webui/repositories/clip-interrogator/clip_interrogator/data/* /s  0.0s
 => CACHED [auto stage-1  6/11] RUN --mount=type=cache,target=/root/.cache/pip   pip install -r /stable-diffusion-webui/repositories/CodeFormer/requirements.txt        0.0s
 => CACHED [auto stage-1  7/11] RUN --mount=type=cache,target=/root/.cache/pip   pip install pyngrok xformers   git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d  0.0s
 => CACHED [auto stage-1  8/11] COPY . /docker                                                                                                                          0.0s
 => CACHED [auto stage-1  9/11] RUN   sed -i 's/in_app_dir = .*/in_app_dir = True/g' /opt/conda/lib/python3.10/site-packages/gradio/routes.py &&   git config --global  0.0s
 => CACHED [auto stage-1 10/11] WORKDIR /stable-diffusion-webui                                                                                                         0.0s
 => [auto] exporting to image                                                                                                                                           0.0s
 => => exporting layers                                                                                                                                                 0.0s
 => => writing image sha256:36ba8fb9c0bd9085554c0f9cf076ed7b266f24f0f28494af43000a36bb5a944e                                                                            0.0s
 => => naming to docker.io/library/sd-auto:68                                                                                                                           0.0s
[+] Running 1/0
 ✔ Container webui-docker-auto-1  Created                                                                                                                               0.0s 
Attaching to auto-1
auto-1  | /stable-diffusion-webui
auto-1  | total 704K
auto-1  | drwxr-xr-x 1 root root 4.0K Nov 20 22:19 .
auto-1  | drwxr-xr-x 1 root root 4.0K Nov 20 21:53 ..
auto-1  | -rw-r--r-- 1 root root   48 Nov 20 21:08 .eslintignore
auto-1  | -rw-r--r-- 1 root root 3.4K Nov 20 21:08 .eslintrc.js
auto-1  | drwxr-xr-x 8 root root 4.0K Nov 20 21:08 .git
auto-1  | -rw-r--r-- 1 root root   55 Nov 20 21:08 .git-blame-ignore-revs
auto-1  | drwxr-xr-x 4 root root 4.0K Nov 20 21:08 .github
auto-1  | -rw-r--r-- 1 root root  495 Nov 20 21:08 .gitignore
auto-1  | -rw-r--r-- 1 root root  119 Nov 20 21:08 .pylintrc
auto-1  | -rw-r--r-- 1 root root  33K Nov 20 21:08 CHANGELOG.md
auto-1  | -rw-r--r-- 1 root root  243 Nov 20 21:08 CITATION.cff
auto-1  | -rw-r--r-- 1 root root  657 Nov 20 21:08 CODEOWNERS
auto-1  | -rw-r--r-- 1 root root  35K Nov 20 21:08 LICENSE.txt
auto-1  | -rw-r--r-- 1 root root  12K Nov 20 21:08 README.md
auto-1  | drwxr-xr-x 2 root root 4.0K Nov 20 21:53 __pycache__
auto-1  | -rw-r--r-- 1 root root 5.5K Nov 20 22:19 cache.json
auto-1  | lrwxrwxrwx 1 root root   29 Nov 20 22:19 config.json -> /data/config/auto/config.json
auto-1  | lrwxrwxrwx 1 root root   31 Nov 20 22:19 config_states -> /data/config/auto/config_states
auto-1  | drwxr-xr-x 2 root root 4.0K Nov 20 21:08 configs
auto-1  | lrwxrwxrwx 1 root root   16 Nov 20 22:19 embeddings -> /data/embeddings
auto-1  | -rw-r--r-- 1 root root  167 Nov 20 21:08 environment-wsl2.yaml
auto-1  | lrwxrwxrwx 1 root root   28 Nov 20 22:19 extensions -> /data/config/auto/extensions
auto-1  | drwxr-xr-x 1 root root 4.0K Nov 20 21:08 extensions-builtin
auto-1  | drwxr-xr-x 2 root root 4.0K Nov 20 21:08 html
auto-1  | drwxr-xr-x 2 root root 4.0K Nov 20 21:09 interrogate
auto-1  | drwxr-xr-x 2 root root 4.0K Nov 20 21:08 javascript
auto-1  | -rw-r--r-- 1 root root 1.3K Nov 20 21:08 launch.py
auto-1  | drwxr-xr-x 2 root root 4.0K Nov 20 21:08 localizations
auto-1  | lrwxrwxrwx 1 root root   12 Nov 20 22:19 models -> /data/models
auto-1  | drwxr-xr-x 1 root root 4.0K Nov 20 21:53 modules
auto-1  | -rw-r--r-- 1 root root  185 Nov 20 21:08 package.json
auto-1  | -rw-r--r-- 1 root root  763 Nov 20 21:08 pyproject.toml
auto-1  | drwxr-xr-x 1 root root 4.0K Oct 30 20:01 repositories
auto-1  | -rw-r--r-- 1 root root   49 Nov 20 21:08 requirements-test.txt
auto-1  | -rw-r--r-- 1 root root  360 Nov 20 21:08 requirements.txt
auto-1  | -rw-r--r-- 1 root root  556 Nov 20 21:08 requirements_versions.txt
auto-1  | -rw-r--r-- 1 root root 411K Nov 20 21:08 screenshot.png
auto-1  | -rw-r--r-- 1 root root 4.7K Nov 20 21:08 script.js
auto-1  | drwxr-xr-x 1 root root 4.0K Nov 20 21:53 scripts
auto-1  | -rw-r--r-- 1 root root  21K Nov 20 21:08 style.css
auto-1  | lrwxrwxrwx 1 root root   28 Nov 20 22:19 styles.csv -> /data/config/auto/styles.csv
auto-1  | drwxr-xr-x 3 root root 4.0K Nov 20 21:08 test
auto-1  | drwxr-xr-x 2 root root 4.0K Nov 20 21:08 textual_inversion_templates
auto-1  | lrwxrwxrwx 1 root root   32 Nov 20 22:19 ui-config.json -> /data/config/auto/ui-config.json
auto-1  | -rw-r--r-- 1 root root  670 Nov 20 21:08 webui-macos-env.sh
auto-1  | -rw-r--r-- 1 root root   84 Nov 20 21:08 webui-user.bat
auto-1  | -rw-r--r-- 1 root root 1.4K Nov 20 21:08 webui-user.sh
auto-1  | -rw-r--r-- 1 root root 2.2K Nov 20 21:08 webui.bat
auto-1  | -rw-r--r-- 1 root root 5.4K Nov 20 21:08 webui.py
auto-1  | -rwxr-xr-x 1 root root 8.0K Nov 20 21:08 webui.sh
auto-1  | Mounted embeddings
auto-1  | Mounted .cache
auto-1  | Mounted styles.csv
auto-1  | Mounted ui-config.json
auto-1  | Mounted models
auto-1  | Mounted .cache
auto-1  | Mounted config_states
auto-1  | Mounted config.json
auto-1  | Mounted extensions
auto-1  | Installing extension dependencies (if any)
auto-1  | Checkpoint sd_xl_base_1.0.safetensors [31e35c80fc] not found; loading fallback sd-v1-5-inpainting.ckpt [c6bbc15e32]
auto-1  | Loading weights [c6bbc15e32] from /stable-diffusion-webui/models/Stable-diffusion/sd-v1-5-inpainting.ckpt
auto-1  | Running on local URL:  http://0.0.0.0:7860
auto-1  | 
auto-1  | To create a public link, set `share=True` in `launch()`.
auto-1  | Startup time: 6.5s (import torch: 2.6s, import gradio: 0.9s, setup paths: 1.3s, initialize shared: 0.1s, other imports: 0.5s, load scripts: 0.3s, create ui: 0.3s, gradio launch: 0.2s).
auto-1  | Creating model from config: /stable-diffusion-webui/configs/v1-inpainting-inference.yaml
auto-1  | Loading VAE weights specified in settings: /stable-diffusion-webui/models/VAE/sdxl_vae.safetensors
auto-1  | Applying attention optimization: xformers... done.
auto-1  | Model loaded in 5.0s (load weights from disk: 2.6s, create model: 0.3s, apply weights to model: 1.1s, apply half(): 0.4s, calculate empty prompt: 0.4s).
auto-1  | Reusing loaded model sd-v1-5-inpainting.ckpt [c6bbc15e32] to load sdXL_v10VAEFix.safetensors
auto-1  | Calculating sha256 for /stable-diffusion-webui/models/Stable-diffusion/sdXL_v10VAEFix.safetensors: e6bb9ea85bbf7bf6478a7c6d18b71246f22e95d41bcdd80ed40aa212c33cfeff
auto-1  | Loading weights [e6bb9ea85b] from /stable-diffusion-webui/models/Stable-diffusion/sdXL_v10VAEFix.safetensors
auto-1  | Creating model from config: /stable-diffusion-webui/repositories/generative-models/configs/inference/sd_xl_base.yaml
auto-1  | ERROR:root:Model config for ViT-bigG-14 not found; available models ['mt5-base-ViT-B-32', 'mt5-xl-ViT-H-14', 'RN50', 'RN50-quickgelu', 'RN50x4', 'RN50x16', 'RN50x64', 'RN101', 'RN101-quickgelu', 'roberta-ViT-B-32', 'timm-convnext_base', 'timm-convnext_large', 'timm-convnext_xlarge', 'timm-efficientnetv2_rw_s', 'timm-resnetaa50d', 'timm-swin_base_patch4_window7_224', 'timm-vit_medium_patch16_gap_256', 'timm-vit_relpos_medium_patch16_cls_224', 'ViT-B-16', 'ViT-B-16-plus', 'ViT-B-16-plus-240', 'ViT-B-32', 'ViT-B-32-plus-256', 'ViT-B-32-quickgelu', 'ViT-e-14', 'ViT-g-14', 'ViT-G-14', 'ViT-H-14', 'ViT-H-16', 'ViT-L-14', 'ViT-L-14-280', 'ViT-L-14-336', 'ViT-L-16', 'ViT-L-16-320', 'ViT-M-16', 'ViT-M-16-alt', 'ViT-M-32', 'ViT-M-32-alt', 'ViT-S-16', 'ViT-S-16-alt', 'ViT-S-32', 'ViT-S-32-alt', 'xlm-roberta-base-ViT-B-32', 'xlm-roberta-large-ViT-H-14'].
auto-1  | creating model quickly: RuntimeError
auto-1  | Traceback (most recent call last):
auto-1  |   File "/opt/conda/lib/python3.10/threading.py", line 973, in _bootstrap
auto-1  |     self._bootstrap_inner()
auto-1  |   File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
auto-1  |     self.run()
auto-1  |   File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
auto-1  |     result = context.run(func, *args)
auto-1  |   File "/opt/conda/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
auto-1  |     response = f(*args, **kwargs)
auto-1  |   File "/stable-diffusion-webui/modules/ui_settings.py", line 272, in <lambda>
auto-1  |     fn=lambda value, k=k: self.run_settings_single(value, key=k),
auto-1  |   File "/stable-diffusion-webui/modules/ui_settings.py", line 90, in run_settings_single
auto-1  |     if value is None or not opts.set(key, value):
auto-1  |   File "/stable-diffusion-webui/modules/options.py", line 140, in set
auto-1  |     option.onchange()
auto-1  |   File "/stable-diffusion-webui/modules/call_queue.py", line 13, in f
auto-1  |     res = func(*args, **kwargs)
auto-1  |   File "/stable-diffusion-webui/modules/initialize_util.py", line 170, in <lambda>
auto-1  |     shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: sd_models.reload_model_weights()), call=False)
auto-1  |   File "/stable-diffusion-webui/modules/sd_models.py", line 751, in reload_model_weights
auto-1  |     load_model(checkpoint_info, already_loaded_state_dict=state_dict)
auto-1  |   File "/stable-diffusion-webui/modules/sd_models.py", line 602, in load_model
auto-1  |     sd_model = instantiate_from_config(sd_config.model)
auto-1  |   File "/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/util.py", line 89, in instantiate_from_config
auto-1  |     return get_obj_from_str(config["target"])(**config.get("params", dict()))
auto-1  |   File "/stable-diffusion-webui/repositories/generative-models/sgm/models/diffusion.py", line 61, in __init__
auto-1  |     self.conditioner = instantiate_from_config(
auto-1  |   File "/stable-diffusion-webui/repositories/generative-models/sgm/util.py", line 175, in instantiate_from_config
auto-1  |     return get_obj_from_str(config["target"])(**config.get("params", dict()))
auto-1  |   File "/stable-diffusion-webui/repositories/generative-models/sgm/modules/encoders/modules.py", line 88, in __init__
auto-1  |     embedder = instantiate_from_config(embconfig)
auto-1  |   File "/stable-diffusion-webui/repositories/generative-models/sgm/util.py", line 175, in instantiate_from_config
auto-1  |     return get_obj_from_str(config["target"])(**config.get("params", dict()))
auto-1  |   File "/stable-diffusion-webui/repositories/generative-models/sgm/modules/encoders/modules.py", line 428, in __init__
auto-1  |     model, _, _ = open_clip.create_model_and_transforms(
auto-1  |   File "/stable-diffusion-webui/modules/sd_disable_initialization.py", line 65, in create_model_and_transforms_without_pretrained
auto-1  |     return self.create_model_and_transforms(*args, pretrained=None, **kwargs)
auto-1  |   File "/opt/conda/lib/python3.10/site-packages/open_clip/factory.py", line 201, in create_model_and_transforms
auto-1  |     model = create_model(
auto-1  |   File "/opt/conda/lib/python3.10/site-packages/open_clip/factory.py", line 131, in create_model
auto-1  |     raise RuntimeError(f'Model config for {model_name} not found.')
auto-1  | RuntimeError: Model config for ViT-bigG-14 not found.
auto-1  | 
auto-1  | Failed to create model quickly; will retry using slow method.
auto-1  | ERROR:root:Model config for ViT-bigG-14 not found; available models ['mt5-base-ViT-B-32', 'mt5-xl-ViT-H-14', 'RN50', 'RN50-quickgelu', 'RN50x4', 'RN50x16', 'RN50x64', 'RN101', 'RN101-quickgelu', 'roberta-ViT-B-32', 'timm-convnext_base', 'timm-convnext_large', 'timm-convnext_xlarge', 'timm-efficientnetv2_rw_s', 'timm-resnetaa50d', 'timm-swin_base_patch4_window7_224', 'timm-vit_medium_patch16_gap_256', 'timm-vit_relpos_medium_patch16_cls_224', 'ViT-B-16', 'ViT-B-16-plus', 'ViT-B-16-plus-240', 'ViT-B-32', 'ViT-B-32-plus-256', 'ViT-B-32-quickgelu', 'ViT-e-14', 'ViT-g-14', 'ViT-G-14', 'ViT-H-14', 'ViT-H-16', 'ViT-L-14', 'ViT-L-14-280', 'ViT-L-14-336', 'ViT-L-16', 'ViT-L-16-320', 'ViT-M-16', 'ViT-M-16-alt', 'ViT-M-32', 'ViT-M-32-alt', 'ViT-S-16', 'ViT-S-16-alt', 'ViT-S-32', 'ViT-S-32-alt', 'xlm-roberta-base-ViT-B-32', 'xlm-roberta-large-ViT-H-14'].
auto-1  | changing setting sd_model_checkpoint to sdXL_v10VAEFix.safetensors: RuntimeError
auto-1  | Traceback (most recent call last):
auto-1  |   File "/stable-diffusion-webui/modules/options.py", line 140, in set
auto-1  |     option.onchange()
auto-1  |   File "/stable-diffusion-webui/modules/call_queue.py", line 13, in f
auto-1  |     res = func(*args, **kwargs)
auto-1  |   File "/stable-diffusion-webui/modules/initialize_util.py", line 170, in <lambda>
auto-1  |     shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: sd_models.reload_model_weights()), call=False)
auto-1  |   File "/stable-diffusion-webui/modules/sd_models.py", line 751, in reload_model_weights
auto-1  |     load_model(checkpoint_info, already_loaded_state_dict=state_dict)
auto-1  |   File "/stable-diffusion-webui/modules/sd_models.py", line 611, in load_model
auto-1  |     sd_model = instantiate_from_config(sd_config.model)
auto-1  |   File "/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/util.py", line 89, in instantiate_from_config
auto-1  |     return get_obj_from_str(config["target"])(**config.get("params", dict()))
auto-1  |   File "/stable-diffusion-webui/repositories/generative-models/sgm/models/diffusion.py", line 61, in __init__
auto-1  |     self.conditioner = instantiate_from_config(
auto-1  |   File "/stable-diffusion-webui/repositories/generative-models/sgm/util.py", line 175, in instantiate_from_config
auto-1  |     return get_obj_from_str(config["target"])(**config.get("params", dict()))
auto-1  |   File "/stable-diffusion-webui/repositories/generative-models/sgm/modules/encoders/modules.py", line 88, in __init__
auto-1  |     embedder = instantiate_from_config(embconfig)
auto-1  |   File "/stable-diffusion-webui/repositories/generative-models/sgm/util.py", line 175, in instantiate_from_config
auto-1  |     return get_obj_from_str(config["target"])(**config.get("params", dict()))
auto-1  |   File "/stable-diffusion-webui/repositories/generative-models/sgm/modules/encoders/modules.py", line 428, in __init__
auto-1  |     model, _, _ = open_clip.create_model_and_transforms(
auto-1  |   File "/opt/conda/lib/python3.10/site-packages/open_clip/factory.py", line 201, in create_model_and_transforms
auto-1  |     model = create_model(
auto-1  |   File "/opt/conda/lib/python3.10/site-packages/open_clip/factory.py", line 131, in create_model
auto-1  |     raise RuntimeError(f'Model config for {model_name} not found.')
auto-1  | RuntimeError: Model config for ViT-bigG-14 not found.
auto-1  | 
```

**Which UI**

auto

**Hardware / Software**

- OS: Arch Linux
- Docker Version: 24.0.7
- Docker compose version: 2.23.1
- Repo version: 3e67f559d43b53faeb4a32b63c8b89391f0b7248
- RAM: 32 Gb
- GPU/VRAM: Nvidia RTX 4090 / 24 Gb

**Steps to Reproduce**

1.
  ```
  git clone https://github.com/AbdBarho/stable-diffusion-webui-docker.git
  cd stable-diffusion-webui-docker
  docker compose --profile download up --build
  docker compose --profile auto up --build
  ```
2. SD 1.5 loads fine and is usable at <http://localhost:7860>. `Ctrl+C` to stop docker compose.
3. Download the SD XL 1.0 base and refiner from civitai or huggingface.
4. 
  ```
  mv sdXL_v10RefinerVAEFix.safetensors sdXL_v10VAEFix.safetensors data/models/Stable-diffusion/`
  docker compose --profile auto up --build
  ```
5. Loading SD XL 1.0 fails in the webui with `RuntimeError: Model config for ViT-bigG-14 not found.`

**Additional context**

Related issues:

- [RuntimeError for v1.5.0-RC-2-gb010eea5 when loading sd xl 0.9 model #11870](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/11870)
- [Bug: #12014](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/12014)

It seems the solution is `pip install open-clip-torch==2.20.0`, however, when I added this to the auto Dockerfile, it fails with:

```
12.36 Collecting xformers
12.36   Obtaining dependency information for xformers from https://files.pythonhosted.org/packages/bb/9c/bb1a40d5e8db2b34dd6e6c0f851e86b38a3d0840fff1bf14240eff7d3da6/xformers-0.0.22.post7-cp310-cp310-manylinux2014_x86_64.whl.metadata
12.37   Using cached xformers-0.0.22.post7-cp310-cp310-manylinux2014_x86_64.whl.metadata (1.0 kB)
12.37 ERROR: Cannot install open-clip-torch 2.7.0 (from git+https://github.com/mlfoundations/open_clip.git@bb6e834e9c70d9c27d0dc3ecedeebeaeb1ffad6b) and open-clip-torch==2.20.0 because these package versions have conflicting dependencies.
12.37 
12.37 The conflict is caused by:
12.37     The user requested open-clip-torch==2.20.0
12.37     The user requested open-clip-torch 2.7.0 (from git+https://github.com/mlfoundations/open_clip.git@bb6e834e9c70d9c27d0dc3ecedeebeaeb1ffad6b)
12.37 
12.37 To fix this you could try to:
12.37 1. loosen the range of package versions you've specified
12.37 2. remove package versions to allow pip attempt to solve the dependency conflict
12.37 
12.37 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

Reverting to a2561f2659234c1adf69ccbcd302cb9578387729 fixes the issue, as long as I add `pip install httpx==0.24.1` to the auto Dockerfile, to fix [this issue](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13236).

### PR DESCRIPTION
**Pull request by jsjolund**
Fixes #615.

Updates `open-clip-torch` to the one specified in auto's [requirements_versions.txt](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/requirements_versions.txt#L18).

### CODE REVIEW

**Comment by LeagueOfPoro** [comment]
Tested, lgtm

**Comment by mashb1t** [comment]
@AbdBarho it would be great if you could merge this adjustment (or use hash bc247f6ece17d4bc6735739a7a8c5ce7d8ecd6a3) as this is necessary to be able to generate anything with A1111

**Review by fadenb — APPROVED** [review]
Change works for me and fixes the issue that resulted in `ERROR:root:Model config for ViT-bigG-14 not found` error with SDXL models :)

**Comment by larryhopecode** [comment]
This fix works fine!

**Review by larryhopecode — APPROVED** [review]

**Review by larryhopecode — COMMENTED** [review]
Sync the version of Open Clip to 2.20.0

**Review by AbdBarho — DISMISSED** [review]
Thank you for this and sorry for being late. Happy new year

**Pull request merged**
